### ISSUE TITLE
Segfault if used with tarantool debug build

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/memcached#59]
Got segfault on both master and this patchset (https://github.com/tarantool/memcached/pull/54) on tarantool 2.5.0-62-gbb7c3d167 (debug) when run tests (cd test && ./test-run.py).

```
#0  0x00007f3f837665f1 in raise () from /lib64/libc.so.6
#1  0x00007f3f8375053b in abort () from /lib64/libc.so.6
#2  0x000056508e4b15b7 in sig_fatal_cb (signo=11, siginfo=0x7f3f6cb7f3f0, context=0x7f3f6cb7f2c0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/main.cc:301
#3  <signal handler called>
#4  0x00007f3f84767eab in slab_from_ptr (ptr=0x7f3f810300a0, slab_mask=0) at /home/alex/p/tarantool-meta/memcached/third_party/small/small/slab_cache.h:203
#5  0x00007f3f847680ce in mempool_free (pool=0x56508feebb50, ptr=0x7f3f810300a0) at /home/alex/p/tarantool-meta/memcached/third_party/small/small/mempool.h:274
#6  0x00007f3f84768416 in iobuf_delete (ibuf=0x7f3f810300a0, obuf=0x7f3f81040480) at /home/alex/p/tarantool-meta/memcached/memcached/internal/network.c:69
#7  0x00007f3f8476acf8 in memcached_handler (p=0x56508feec040, fd=22) at /home/alex/p/tarantool-meta/memcached/memcached/internal/memcached.c:258
#8  0x000056508e675c6b in lj_vm_ffi_call () at buildvm_x86.dasc:2578
#9  0x000056508e69bfe9 in lj_ccall_func (L=L@entry=0x4149e370, cd=<optimized out>) at lj_ccall.c:1150
#10 0x000056508e6716c8 in lj_cf_ffi_meta___call (L=0x4149e370) at lib_ffi.c:230
#11 0x000056508e673cbb in lj_BC_FUNCC () at buildvm_x86.dasc:809
#12 0x000056508e650a56 in lua_pcall (L=0x4149e370, nargs=<optimized out>, nresults=-1, errfunc=<optimized out>) at lj_api.c:1158
#13 0x000056508e5e4822 in luaT_call (L=0x4149e370, nargs=3, nreturns=-1) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lua/utils.c:1053
#14 0x000056508e5dd150 in lua_fiber_run_f (ap=0x7f3f81001470) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lua/fiber.c:443
#15 0x000056508e4b0e69 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x56508e5dd0dc <lua_fiber_run_f>, ap=0x7f3f81001470)
    at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/fiber.h:782
#16 0x000056508e606a71 in fiber_loop (data=0x0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/fiber.c:869
#17 0x000056508e7493b4 in coro_init () at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/third_party/coro/coro.c:110
```
https://github.com/tarantool/memcached/pull/54#issuecomment-636057474

**Comment by LeonidVas** [comment]
After a brief research of the bug, it seems that the problem is in different versions of the “small” library used in the tarantool and memcached module.
The proofs:
- If the "small" will be checkout to the same commit as in tarantool, the problem will disappear.
- if tarantool will be checkout to https://github.com/tarantool/tarantool/commit/2c27c24865399b837e7d13342445bfe18db1d68d, the problem will disappear.

**Comment by LeonidVas** [comment]
As I understood the problem is this:
Tarantool is export the next symbols:
```
└──╼ nm -gD ./src/tarantool | grep mempool
00000000007cc1a1 T mempool_alloc
00000000007cbfac T mempool_create_with_order
00000000007cc115 T mempool_destroy
00000000007d1000 T mempool_iterator_create
00000000007d104b T mempool_iterator_next
00000000007cc34d T mempool_stats
```
Memcached uses the next functions:
mempool_create (defined in small/small/mempool.h) which uses mempool_create_with_order()
mempool_free((defined in small/small/mempool.h)
After https://github.com/tarantool/small/commit/0ce1268e4112c7f9c393116377e665b8666772eb  the size of the struct mempool has been changed (was changed the size of mslab_tree_t).

The reason of the bug is the next: when initializing a struct mempool in mempool_create(memcached version) mempool_create_with_order is called(tarantool version with other struct mempool size), where some fields of the struct mempool are assigned. After that, the corrupted struct mempool will be used in mempool_free(memcached version). And, "BAM!", segfault when trying to use a NULL pointer.

**Comment by LeonidVas** [comment]
It seems that an updating the version of the "small" library will fix memcached for tarantool> = 1.10 .

**Comment by Totktonada** [comment]
I vote to workaround this for now for tarantool >= 1.10 and leave the issue open to investigate further.

**Comment by Totktonada** [comment]
NB: Would some ABI compliance checker (say, [this](https://lvc.github.io/abi-compliance-checker/)) help us with detecting ABI incompatibility in small?

**Comment by LeonidVas** [comment]
> NB: Would some ABI compliance checker (say, [this](https://lvc.github.io/abi-compliance-checker/)) help us with detecting ABI incompatibility in small?

If I understand correctly it's not solve the problem, because now we have a situation when the memcached version implicitly depends on the tarantool "small" version. And now it should be synchronously update or rollback.

**Comment by Totktonada** [comment]
Worked around in PR #60.

**Comment by Totktonada** [comment]
But a proper fix should be implemented in a long term.

**Comment by Totktonada** [comment]
Curious fact: everything works until [2.5.0-42-g03790ac55](https://github.com/tarantool/tarantool/commit/03790ac5510648d1d9648bb2281857a7992d0593) ('cmake: remove dynamic-list linker option'), which is fix of [#2971](https://github.com/tarantool/tarantool/issues/2971) ('Unhide back all symbols in 1.7+'). (I verified it.)

**Comment by LeonidVas** [comment]
> Curious fact: everything works until [2.5.0-42-g03790ac55](https://github.com/tarantool/tarantool/commit/03790ac5510648d1d9648bb2281857a7992d0593) ('cmake: remove dynamic-list linker option'), which is fix of [#2971](https://github.com/tarantool/tarantool/issues/2971) ('Unhide back all symbols in 1.7+'). (I verified it.)

Yep. If tarantool will hides symbols, the problem go away). Memcached will use only its own version of small.

**Comment by Totktonada** [comment]
`-Wl,-Bsymbolic-functions` may help here. See the following pull requests to dive into the topic:

https://github.com/tarantool/smtp/pull/32
https://github.com/tarantool/smtp/pull/33

**Comment by ligurio** [comment]
Possible similar fix was applied in smtp module https://github.com/tarantool/smtp/blob/master/smtp/CMakeLists.txt#L39-L65

**Comment by Totktonada** [comment]
## Background information

We're going to decouple tarantool's runtime arena and a slab cache upward the
arena from memcached's arena and slab cache, because tarantool's small version
was updated in 2.10.0-beta1-315-g173ce9fbb ('small: fix incorrect mempool
group creation'). It will be done in the scope of #96.

And now I want to return here to make sure that all problems around
small-in-the-module and small-in-tarantool are resolved.

The key fact here is that we have certain range of tarantool versions, where
symbols are open. Everything aside this range should be okay (after #96 fix).
We should answer to the question: whether we can hold a particular small
version in memcached and be sure that the symbols clash does not break
anything.

Symbols was visible by default since 2.5.0-42-g03790ac55 ('cmake: remove
dynamic-list linker option') till 2.9.0-244-g5ceabb378 ('cmake: hide tarantool
symbols back'). It corresponds to the following releases:

* 2.5.1, 2.5.2, 2.5.3
* 2.6.1, 2.6.2, 2.6.3
* 2.7.1, 2.7.2, 2.7.3
* 2.8.1, 2.8.2, 2.8.3 (maybe future 2.8.*, if we'll release them)

memcached's small version is 1.1-63-g3df5050.

Tarantool's small versions:

| Tarantool           | Small           |
| ------------------- | --------------- |
| 2.5.1               | 1.1-71-gfcac155 |
| 2.5.2               | 1.1-71-gfcac155 |
| 2.5.3               | 1.1-77-g3ae6cbb |
| 2.6.1               | 1.1-71-gfcac155 |
| 2.6.2               | 1.1-77-g3ae6cbb |
| 2.6.3               | 1.1-81-g279fa38 |
| 2.7.1               | 1.1-77-g3ae6cbb |
| 2.7.2               | 1.1-81-g279fa38 |
| 2.7.3               | 1.1-82-g781fd38 |
| 2.8.1               | 1.1-81-g279fa38 |
| 2.8.2               | 1.1-82-g781fd38 |
| 2.8.3               | 1.1-82-g781fd38 |
| 2.8.3-63-gb96997083 | 1.1-82-g781fd38 |

*Note: small was bumped in 2.5.0-42-g03790ac55 by a mistake and reverted back
in 2.5.0-43-g61d2cb64f.*

## Analysis

Here I want to do an attepmt to estimate small's changes in terms of ABI
compatibility. The comments for commits below attempt to answer the question:
why it cannot affect the memcached module work.

* [1.1-63-g3df5050][1.1-63-g3df5050].

  Base version (used by memcached).
* [1.1-64-g0e4fd61][1.1-64-g0e4fd61] ('rlist: use built-in offsetof() when
  possible')

  Should not actually change a behaviour, but rather eliminate a clang
  warning.
* [1.1-65-g79c7b08][1.1-65-g79c7b08] ('travis-ci: update the list of supported
  distributions')

  CI update.
* [1.1-66-g5706060][1.1-66-g5706060] ('travis-ci: push to 2.3 and 2.4
  repositories')

  CI update.
* [1.1-67-gcd7c005][1.1-67-gcd7c005] ('lsregion: fix slab_unmap() called on
  malloced slab')

  We don't use lsregion in the module.
* [1.1-68-gd9f8079][1.1-68-gd9f8079] ('lsregion: introduce aligned alloc')

  It is again about lsregion, so irrelevant for us.
* [1.1-69-g7546462][1.1-69-g7546462] ('region: new region_alloc_array, updated
  alloc_object')

  It is about `region_alloc_object()` and `region_alloc_array()` macros,
  irrelevant for us.
* [1.1-70-g34eb29d][1.1-70-g34eb29d] ('test: update lsregion .result file')

  It only updates a test.
* [1.1-71-gfcac155][1.1-71-gfcac155] ('test: don't use not aligned size for
  mempool')

  It only updates a test.

  Not relevant here, but there is an interesting note in the commit message:

  > Mempool expects aligned object size.

  Hm. If it the general rule, then it should be either adjusted or asserted in
  `mempool_create()`. If not, it is not clear, when it is applicable and when
  not. And what are consequences on x86_64 if we violate this rule.

  Maybe it was so till 1.1-79-g799f109 (see `mempool.c` changes) and is not
  actual for recent small?
* [1.1-72-g8167b86][1.1-72-g8167b86] ('Fix Centos6 build failed')

  RPM spec update.
* [1.1-73-g9ee874c][1.1-73-g9ee874c] ('Fix build error')

  It fixes a build fail (of a test) that was introduced in 1.1-71-gfcac155.
* [1.1-74-g2e90bcc][1.1-74-g2e90bcc] ('Remove Ubuntu 19.04 Disco')

  CI update.
* [1.1-75-g6c8846c][1.1-75-g6c8846c] ('small: implement new size class
  evaluation')

  It is append-only change. Should be okay.
* [1.1-76-g59b5ccc][1.1-76-g59b5ccc] ('test: add small allocator performance
  test')

  Only adds a test.
* [1.1-77-g3ae6cbb][1.1-77-g3ae6cbb] ('small: changed small allocator pool
  management')

  All changes are about `small_alloc()`. We don't use it in the module.
* [1.1-78-g29bf0cb][1.1-78-g29bf0cb] ('replace strong cas with weak version
  inside loops')

  Calling of module's small function or tarantool's one has exactly same
  effect. It should be safe.
* [1.1-79-g799f109][1.1-79-g799f109] ('small: add granularity option to
  small_alloc_create')

  Regarding `mempool.c` changes: those definitely will not make things worse.

  Regarding `small_alloc()` changes: it is irrelevant for us, because it is
  not used in the module.
* [1.1-80-g2ab83e1][1.1-80-g2ab83e1] ('test: fix error in flaky test')

  Test fix.
* [1.1-81-g279fa38][1.1-81-g279fa38] ('test: obuf test refactoring')

  Test change.
* [1.1-82-g781fd38][1.1-82-g781fd38] ('build: fix tarantool build failure on
  xcode 12.5')

  It only changes include files placement. No ABI changes.

So the changes look safe in terms of ABI compatibility (taking into account the
fact that we use only mempool, region, ibuf and obuf in the module).

[1.1-63-g3df5050]: https://github.com/tarantool/small/commit/3df5050171d040bfe5717b4bddf57da3b312ffe4
[1.1-64-g0e4fd61]: https://github.com/tarantool/small/commit/0e4fd619344c44f533829bbfd8d9cf7de306360b
[1.1-65-g79c7b08]: https://github.com/tarantool/small/commit/79c7b08d89be7be3d1275a3028755dafa57484bd
[1.1-66-g5706060]: https://github.com/tarantool/small/commit/5706060cc81121733a9db51bf25fd8c5eee10c55
[1.1-67-gcd7c005]: https://github.com/tarantool/small/commit/cd7c005733e22a1bae4882c236f60267b1a7b6f3
[1.1-68-gd9f8079]: https://github.com/tarantool/small/commit/d9f80798fa9bc5e08786dab3d31f8a8141347080
[1.1-69-g7546462]: https://github.com/tarantool/small/commit/75464628e3a5e471e1b9cd07fb0d80866e58536a
[1.1-70-g34eb29d]: https://github.com/tarantool/small/commit/34eb29de436a696945a7b3723b835babbce7a14f
[1.1-71-gfcac155]: https://github.com/tarantool/small/commit/fcac155dba18e97b10bc668d1a2fae01184adc13
[1.1-72-g8167b86]: https://github.com/tarantool/small/commit/8167b86eb9f93a9cd6fe71b4d987444aa3e860f4
[1.1-73-g9ee874c]: https://github.com/tarantool/small/commit/9ee874c2df7e60c388d49d1d6851950477b40c3f
[1.1-74-g2e90bcc]: https://github.com/tarantool/small/commit/2e90bcce33ba2caf9d59e5bf0db15a5f5394c3f8
[1.1-75-g6c8846c]: https://github.com/tarantool/small/commit/6c8846c763fc208fdad664e3021028b916d536d8
[1.1-76-g59b5ccc]: https://github.com/tarantool/small/commit/59b5ccc508e4fe24fb2d93df7ed21b5ba81c0f7e
[1.1-77-g3ae6cbb]: https://github.com/tarantool/small/commit/3ae6cbb4b51bb327aea30acaa83098bb25b03156
[1.1-78-g29bf0cb]: https://github.com/tarantool/small/commit/29bf0cb2b6dd46431ef82ea993a5f915c7e42c7e
[1.1-79-g799f109]: https://github.com/tarantool/small/commit/799f109b8f85801b30c81e399ea8b6a3dfdb4784
[1.1-80-g2ab83e1]: https://github.com/tarantool/small/commit/2ab83e1b23f8f34d3dcc7ad1a7c5edc364d4386e
[1.1-81-g279fa38]: https://github.com/tarantool/small/commit/279fa38ac89be526dcef0a9dd88cf4775367f5c5
[1.1-82-g781fd38]: https://github.com/tarantool/small/commit/781fd38af8d6e07c486caf276a58f77de7c1c39f

## Experiment

Build Tarantool in Debug configuration:

```shell
$ git clean -xffd; git submodule foreach --recursive 'git clean -xffd'
$ git checkout -- .
$ git checkout $TAG
$ rm -r third_party test-run
$ git checkout -- third_party
$ git submodule update --init --recursive
$ <..apply tweaks (seee below)..>
$ cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_FEEDBACK_DAEMON=OFF -DENABLE_BUNDLED_LIBCURL=OFF && make -j
$ make DESTDIR=../$(git describe) install
```

Build Tarantool in RelWithDebInfo configuration:

```shell
<..same as above..>
$ cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_FEEDBACK_DAEMON=OFF -DENABLE_BUNDLED_LIBCURL=OFF && make -j
$ make DESTDIR=../$(git describe)-release install
```

<details>
<summary>Build tweaks</summary>

* `2.5.1`

  ```shell
  $ git show 2.6.0-130-g0ffba1972 test/unit/guava.c | patch -p1
  $ git show 2.10.0-beta1-377-g9c01b325a test/unit/guard.cc | sed s/xmalloc/malloc/ | patch -p1
  ```
* `2.5.2`, `2.5.3`, `2.6.*`, `2.7.*`, `2.8.1`, `2.8.2`

  ```shell
  $ git show 2.10.0-beta1-377-g9c01b325a test/unit/guard.cc | sed s/xmalloc/malloc/ | patch -p1
  ```
</details>

Build memcached in Debug configuration:

```shell
$ cmake . -DCMAKE_BUILD_TYPE=Debug && make
<..ensure that the following line is present..>
-- Could NOT find Small (missing: SMALL_INCLUDE_DIR SMALL_LIBRARY)
<...>
```

Build memcached in RelWithDebInfo configuration:

```shell
$ cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo && make
<..ensure that the following line is present..>
-- Could NOT find Small (missing: SMALL_INCLUDE_DIR SMALL_LIBRARY)
<...>
```

Run memcached tests (against Debug tarantool):

```shell
$ (export PATH="$(realpath ../${TAG}/usr/local/bin):${PATH}"; make test-memcached && make test-memcached-bench)
# or for all tarantool builds at once
$ for TAG in 2.5.{1..3} 2.6.{1..3} 2.7.{1..3} 2.8.{1..3} 2.8.3-63-gb96997083; do (export PATH="$(realpath ../${TAG}/usr/local/bin):${PATH}"; make test-memcached && make test-memcached-bench); done
```

Run memcached tests (against RelWithDebInfo tarantool):

```shell
$ (export PATH="$(realpath ../${TAG}-release/usr/local/bin):${PATH}"; make test-memcached && make test-memcached-bench)
# or for all tarantool builds at once
$ for TAG in 2.5.{1..3} 2.6.{1..3} 2.7.{1..3} 2.8.{1..3} 2.8.3-63-gb96997083; do (export PATH="$(realpath ../${TAG}-release/usr/local/bin):${PATH}"; make test-memcached && make test-memcached-bench); done
```

Note: I have problems with libmemcached build on Gentoo (it seems, it requires
an update from upstream), so I didn't run `make test-memcached-capable`.

memcached master: 1.0.1-40-g5aaac83.
memcached PR #102: commit aa1f6e208e09adcf9b9ac3476fc974ffab0983c4.

Tarantool Debug + memcached Debug:

| Tarantool           | memcached master | memcached master + tests from PR #102 | memcached PR #102 |
| ------------------- | ---------------- | ------------------------------------- | ----------------- |
| 2.5.1               | OK               | OK                                    | OK                |
| 2.5.2               | OK               | OK                                    | OK                |
| 2.5.3               | OK               | OK                                    | OK                |
| 2.6.1               | OK               | OK                                    | OK                |
| 2.6.2               | OK               | OK                                    | OK                |
| 2.6.3               | OK               | OK                                    | OK                |
| 2.7.1               | OK               | OK                                    | OK                |
| 2.7.2               | OK               | OK                                    | OK                |
| 2.7.3               | OK               | OK                                    | OK                |
| 2.8.1               | OK               | OK                                    | OK                |
| 2.8.2               | OK[^1]           | OK                                    | OK                |
| 2.8.3               | OK               | OK                                    | OK                |
| 2.8.3-63-gb96997083 | OK               | OK                                    | OK                |

[^1]: Here I got a fail, which is gone after re-run. It looks irrelevant to the
      symbols clash and I filed #110 against it.

Tarantool Debug + memcached RelWithDebInfo:

| Tarantool           | memcached master | memcached master + tests from PR #102 | memcached PR #102 |
| ------------------- | ---------------- | ------------------------------------- | ----------------- |
| 2.5.1               | OK               | OK                                    | OK                |
| 2.5.2               | OK               | OK                                    | OK                |
| 2.5.3               | OK               | OK                                    | OK                |
| 2.6.1               | OK               | OK                                    | OK                |
| 2.6.2               | OK               | OK                                    | OK                |
| 2.6.3               | OK               | OK                                    | OK                |
| 2.7.1               | OK               | OK                                    | OK                |
| 2.7.2               | OK               | OK                                    | OK                |
| 2.7.3               | OK               | OK                                    | OK                |
| 2.8.1               | OK               | OK                                    | OK                |
| 2.8.2               | OK               | OK                                    | OK                |
| 2.8.3               | OK               | OK                                    | OK                |
| 2.8.3-63-gb96997083 | OK               | OK                                    | OK                |

Tarantool RelWithDebInfo + memcached Debug:

| Tarantool           | memcached master | memcached master + tests from PR #102 | memcached PR #102 |
| ------------------- | ---------------- | ------------------------------------- | ----------------- |
| 2.5.1               | OK               | OK                                    | OK                |
| 2.5.2               | OK               | OK                                    | OK                |
| 2.5.3               | OK               | OK                                    | OK                |
| 2.6.1               | OK               | OK                                    | OK                |
| 2.6.2               | OK               | OK                                    | OK                |
| 2.6.3               | OK               | OK                                    | OK                |
| 2.7.1               | OK               | OK                                    | OK                |
| 2.7.2               | OK               | OK                                    | OK                |
| 2.7.3               | OK               | OK                                    | OK                |
| 2.8.1               | OK               | OK                                    | OK                |
| 2.8.2               | OK               | OK                                    | OK                |
| 2.8.3               | OK               | OK                                    | OK                |
| 2.8.3-63-gb96997083 | OK               | OK                                    | OK                |

Tarantool RelWithDebInfo + memcached RelWithDebInfo:

| Tarantool           | memcached master | memcached master + tests from PR #102 | memcached PR #102 |
| ------------------- | ---------------- | ------------------------------------- | ----------------- |
| 2.5.1               | OK               | OK                                    | OK                |
| 2.5.2               | OK               | OK                                    | OK                |
| 2.5.3               | OK               | OK                                    | OK                |
| 2.6.1               | OK               | OK                                    | OK                |
| 2.6.2               | OK               | OK                                    | OK                |
| 2.6.3               | OK               | OK                                    | OK                |
| 2.7.1               | OK               | OK                                    | OK                |
| 2.7.2               | OK               | OK                                    | OK                |
| 2.7.3               | OK               | OK                                    | OK                |
| 2.8.1               | OK               | OK                                    | OK                |
| 2.8.2               | OK               | OK                                    | OK                |
| 2.8.3               | OK               | OK                                    | OK                |
| 2.8.3-63-gb96997083 | OK               | OK                                    | OK                |

Tests from PR #102 to run on memcached master are
`test/common/instance_api.test.lua` and `test/common/module_api.test.lua` from
commit 549ce31c3c3b2d882c1c01f054451567ae5abb24 ('memcached: use own slab
arena').

## `ibuf_*` symbols.

There is another problem with symbols clash:
https://github.com/tarantool/tarantool/issues/6873. It is about `ibuf_*`
symbols and those symbols are NOT hid in 2.9.0-244-g5ceabb378.

We can attempt to extend the libsmall changes analysis and testing till recent
tarantool versions: current tarantool `master` is on
2.10.0-beta2-213-gcc768ea82 and it is not fixed there. However I can propose a hack.

We can just rename symbols in the module and skip the analysis.

<details>
<summary>PoC patch</summary>

```diff
diff --git a/small/ibuf.c b/small/ibuf.c
index fe3f441..ebcda67 100644
--- a/small/ibuf.c
+++ b/small/ibuf.c
@@ -34,7 +34,7 @@
 
 /** Initialize an input buffer. */
 void
-ibuf_create(struct ibuf *ibuf, struct slab_cache *slabc, size_t start_capacity)
+memcached_small_ibuf_create(struct ibuf *ibuf, struct slab_cache *slabc, size_t start_capacity)
 {
 	ibuf->slabc = slabc;
 	ibuf->buf = ibuf->rpos = ibuf->wpos = ibuf->end = NULL;
@@ -43,7 +43,7 @@ ibuf_create(struct ibuf *ibuf, struct slab_cache *slabc, size_t start_capacity)
 }
 
 void
-ibuf_destroy(struct ibuf *ibuf)
+memcached_small_ibuf_destroy(struct ibuf *ibuf)
 {
 	if (ibuf->buf) {
 		struct slab *slab = slab_from_data(ibuf->buf);
@@ -53,12 +53,12 @@ ibuf_destroy(struct ibuf *ibuf)
 
 /** Free memory allocated by this buffer */
 void
-ibuf_reinit(struct ibuf *ibuf)
+memcached_small_ibuf_reinit(struct ibuf *ibuf)
 {
 	struct slab_cache *slabc = ibuf->slabc;
 	size_t start_capacity = ibuf->start_capacity;
-	ibuf_destroy(ibuf);
-	ibuf_create(ibuf, slabc, start_capacity);
+	memcached_small_ibuf_destroy(ibuf);
+	memcached_small_ibuf_create(ibuf, slabc, start_capacity);
 }
 
 /**
@@ -67,7 +67,7 @@ ibuf_reinit(struct ibuf *ibuf)
  * the beginning.
  */
 void *
-ibuf_reserve_slow(struct ibuf *ibuf, size_t size)
+memcached_small_ibuf_reserve_slow(struct ibuf *ibuf, size_t size)
 {
 	assert(ibuf->wpos + size > ibuf->end);
 	size_t used = ibuf_used(ibuf);
diff --git a/small/ibuf.h b/small/ibuf.h
index 00d7781..691c821 100644
--- a/small/ibuf.h
+++ b/small/ibuf.h
@@ -69,13 +69,13 @@ struct ibuf
 };
 
 void
-ibuf_create(struct ibuf *ibuf, struct slab_cache *slabc, size_t start_capacity);
+memcached_small_ibuf_create(struct ibuf *ibuf, struct slab_cache *slabc, size_t start_capacity);
 
 void
-ibuf_destroy(struct ibuf *ibuf);
+memcached_small_ibuf_destroy(struct ibuf *ibuf);
 
 void
-ibuf_reinit(struct ibuf *ibuf);
+memcached_small_ibuf_reinit(struct ibuf *ibuf);
 
 /** How much data is read and is not parsed yet. */
 static inline size_t
@@ -119,14 +119,14 @@ ibuf_reset(struct ibuf *ibuf)
 }
 
 void *
-ibuf_reserve_slow(struct ibuf *ibuf, size_t size);
+memcached_small_ibuf_reserve_slow(struct ibuf *ibuf, size_t size);
 
 static inline void *
 ibuf_reserve(struct ibuf *ibuf, size_t size)
 {
 	if (ibuf->wpos + size <= ibuf->end)
 		return ibuf->wpos;
-	return ibuf_reserve_slow(ibuf, size);
+	return memcached_small_ibuf_reserve_slow(ibuf, size);
 }
 
 static inline void *
@@ -136,7 +136,7 @@ ibuf_alloc(struct ibuf *ibuf, size_t size)
 	if (ibuf->wpos + size <= ibuf->end)
 		ptr = ibuf->wpos;
 	else {
-		ptr = ibuf_reserve_slow(ibuf, size);
+		ptr = memcached_small_ibuf_reserve_slow(ibuf, size);
 		if (ptr == NULL)
 			return NULL;
 	}
diff --git a/memcached/internal/network.c b/memcached/internal/network.c
index 02126a6..d8deb8a 100644
--- a/memcached/internal/network.c
+++ b/memcached/internal/network.c
@@ -49,7 +49,7 @@ ibuf_new()
 {
 	void *ibuf = mempool_alloc(&ibuf_pool);
 	if (ibuf == NULL) return NULL;
-	ibuf_create((struct ibuf *)ibuf, memcached_slab_cache(), iobuf_readahead);
+	memcached_small_ibuf_create((struct ibuf *)ibuf, memcached_slab_cache(), iobuf_readahead);
 	return ibuf;
 }
 
@@ -65,7 +65,7 @@ obuf_new()
 void
 iobuf_delete(struct ibuf *ibuf, struct obuf *obuf)
 {
-	ibuf_destroy(ibuf);
+	memcached_small_ibuf_destroy(ibuf);
 	obuf_destroy(obuf);
 	mempool_free(&ibuf_pool, ibuf);
 	mempool_free(&obuf_pool, obuf);
```
</details>

Since `ibuf.c` and `ibuf.h` are small (not large, I mean) we can just copy them
into the module source code and rename functions.

After this I'll consider this issue as resolved.
